[package]
name = "digest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest_auth = "0.3.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }
async-trait = "0.1.58"
